### ISSUE TITLE
setsockopt Operation not permitted

### ISSUE THREAD

**Issue by john-d13** [semigodking/redsocks#88]
Hello,

I have been testing the latest fork of redsocks2 dated a week from today.  I have run into an error that prevents transparent mode from functioning. Composed on OpenSSL (make).  When clients try connecting I receive the "setsockopt: Operation not permitted" error.  Likely due to the startup error described below also.

/var/log/messages:

Mar 18 21:54:35 openvpn2-tcp-us-east redsocks[4883]: setsockopt: Operation not permitted
Mar 18 21:54:35 openvpn2-tcp-us-east redsocks[4883]: [10.66.77.6:28320->40.83.21.197:443]: red_connect_relay failed!!!: Operation not permitted

redsocks2 start log:

Mar 18 22:05:54 openvpn2-tcp-us-east systemd: Starting Transparent redirector of any TCP connection to proxy using your firewall...
Mar 18 22:06:04 openvpn2-tcp-us-east systemd: Started Transparent redirector of any TCP connection to proxy using your firewall.
Mar 18 22:06:04 openvpn2-tcp-us-east redsocks[5294]: setsockopt(..., SOL_IP, IP_TRANSPARENT): Operation not permitted
Mar 18 22:06:04 openvpn2-tcp-us-east redsocks[5294]: Continue without TPROXY support
Mar 18 22:06:04 openvpn2-tcp-us-east redsocks[5294]: Failed to load IP addresses from cache file: /tmp/ipcache.txt
Mar 18 22:06:04 openvpn2-tcp-us-east redsocks[5294]: redsocks started with: epoll

Here is my compile logs:

```
root@openvpn2-tcp-us-east redsocks]# make
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
mkdir -p gen
touch gen/.build
rm -f -f gen/version.c.tmp
echo '/* this file is auto-generated during build */' > gen/version.c.tmp
echo '#include "../version.h"' >> gen/version.c.tmp
echo 'const char* redsocks_version = ' >> gen/version.c.tmp
if [ -d .git ]; then \
echo '"redsocks.git/'`git describe --tags`' OpenSSL"'; \
if [ `git status --porcelain | grep -v -c '^??'` != 0 ]; then \
echo '"-unclean"'; \
fi \
else \
echo '"redsocks/0.66 OpenSSL"'; \
fi >> gen/version.c.tmp
echo ';' >> gen/version.c.tmp
mv -f gen/version.c.tmp gen/version.c
cc -MM -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL parser.c main.c redsocks.c log.c direct.c ipcache.c autoproxy.c http-connect.c socks4.c socks5.c http-relay.c base.c base64.c md5.c http-auth.c utils.c redudp.c socks5-udp.c tcpdns.c gen/version.c 2>/dev/null >.depend || \
( \
for I in redsocks.h libc-compat.h list.h encrypt.h tcpdns.h md5.h socks5.h log.h base.h http-auth.h shadowsocks.h parser.h version.h main.h base64.h redudp.h ipcache.h utils.h; do \
export ${I//[-.]/_}_DEPS="`sed '/^\#[ \t]*include \?"\(.*\)".*/!d;s//\1/' $I`"; \
done; \
echo -n >.depend; \
for SRC in parser.c main.c redsocks.c log.c direct.c ipcache.c autoproxy.c http-connect.c socks4.c socks5.c http-relay.c base.c base64.c md5.c http-auth.c utils.c redudp.c socks5-udp.c tcpdns.c gen/version.c; do \
echo -n "${SRC%.c}.o: " >>.depend; \
export SRC_DEPS="`sed '/\#[ \t]*include \?"\(.*\)".*/!d;s//\1/' $SRC | sort`"; \
while true; do \
export SRC_DEPS_OLD="$SRC_DEPS"; \
export SRC_DEEP_DEPS=""; \
for HDR in $SRC_DEPS; do \
eval export SRC_DEEP_DEPS="\"$SRC_DEEP_DEPS \$${HDR//[-.]/_}_DEPS\""; \
done; \
export SRC_DEPS="`echo $SRC_DEPS $SRC_DEEP_DEPS | sed 's/ */\n/g' | sort -u`"; \
test "$SRC_DEPS" = "$SRC_DEPS_OLD" && break; \
done; \
echo $SRC $SRC_DEPS >>.depend; \
done; \
)
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o parser.o parser.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o main.o main.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o redsocks.o redsocks.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o log.o log.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o direct.o direct.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o ipcache.o ipcache.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o autoproxy.o autoproxy.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o http-connect.o http-connect.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o socks4.o socks4.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o socks5.o socks5.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o http-relay.o http-relay.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o base.o base.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o base64.o base64.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o md5.o md5.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o http-auth.o http-auth.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o utils.o utils.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o redudp.o redudp.c
redudp.c:158:13: warning: âbound_udp4_putâ defined but not used [-Wunused-function]
static void bound_udp4_put(const struct sockaddr_in *addr)
^
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o socks5-udp.o socks5-udp.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o tcpdns.o tcpdns.c
tcpdns.c:350:13: warning: âcheck_dns_delayâ defined but not used [-Wunused-function]
static void check_dns_delay()
^
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o gen/version.o gen/version.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -o redsocks2 parser.o main.o redsocks.o log.o direct.o ipcache.o autoproxy.o http-connect.o socks4.o socks5.o http-relay.o base.o base64.o md5.o http-auth.o utils.o redudp.o socks5-udp.o tcpdns.o gen/version.o -levent
```

Configuration file:

```
base {
              log_debug = on;

               log_info = on;

        /* possible `log' values are:
         *   stderr
         *   "file:/path/to/file"
         *   syslog:FACILITY  facility is any of "daemon", "local0"..."local7"
         */
        log = "syslog:daemon";

         daemon = on;

        /* Change uid, gid and root directory, these options require root
         * privilegies on startup.
         * Note, your chroot may requre /etc/localtime if you write log to syslog.
         * Log is opened before chroot & uid changing.
         */
        user = redsocks;
        group = redsocks;
        // chroot = "/var/chroot";

        /* possible `redirector' values are:
         *   iptables   - for Linux
         *   ipf        - for FreeBSD
         *   pf         - for OpenBSD
         *   generic    - some generic redirector that MAY work
         */
        redirector = iptables;

}

redsocks {
        /* `local_ip' defaults to 127.0.0.1 for security reasons,
         * use 0.0.0.0 if you want to listen on every interface.
         * `local_*' are used as port to redirect to.
         */
//      local_ip = 127.0.0.1;
        local_ip = 10.66.77.1;
        local_port = 12345;

        ip = 104.255.66.35;
        port = 19013;

        // known types: socks4, socks5, http-connect, http-relay
        // New types: direct, shadowsocks, https-connect
        type = http-connect;

        // Specify interface for outgoing connections.
        // This is useful when you have multiple connections to
        // internet or when you have VPN connections.
        interface = tun0;

        autoproxy = 0;
        timeout = 10;
}

autoproxy {
    // Specify interface for outgoing connections.
    // This is useful when you have multiple connections to
    // internet or when you have VPN connections.
    // interface = wlan0;

    no_quick_check_seconds = 60; // Directly relay traffic to proxy if an IP
                                 // is found blocked in cache and it has been
                                 // added into cache no earlier than this
                                 // specified number of seconds.
                                 // Set it to 0 if you do not want to perform
                                 // quick check when an IP is found in blocked
                                 // IP cache, thus the connection will be
                                 // redirected to proxy immediately.
    quick_connect_timeout = 3;   // Timeout value when performing quick
                                 // connection check if an IP is found blocked
                                 // in cache.
}

ipcache {
    // Configure IP cache
    cache_size = 4;   // Maximum number of IP's in 1K.
    stale_time = 900; // Seconds to stale an IP in cache since it is added
                      // into cahce.
                      // Set it to 0 to disable cache stale.
    port_check = 1;   // Whether to distinguish port number in address
    cache_file = "/tmp/ipcache.txt"; // File used to store blocked IP's in cache.
    autosave_interval = 3600; // Interval for saving ip cache into file.
                              // Set it to 0 to disable autosave.
    // When autosave_interval and stale_time are both 0, IP cache behaves like
    // a static blacklist.
}
```

**Comment by semigodking** [comment]
Hi @john-d13 ,
redsocks2 fails because of this line in your configuration file. 
``
interface = tun0;
``
There is not enough information to figure out why it fails. One possible reason I can guess is that interface 'tun0' was down and up.  I met similar issue while using n2n.  If you config redsocks to run as root instead of 'redsocks', this issue should be solved.

**Comment by john-d13** [comment]
Thanks for the reply.  I tried your suggestion and it worked,  I am now running the service as root and the error disapears, however,  I still cant get client traffic pushed through redsocks.  I tried updating type http/https to no avail.  The ingress connections are being forwarded to the local redsocks port 12345 but they eventually timeout with no client response.   Any suggestions?


# netstat -an | grep 12345
tcp        0      0 10.66.77.1:12345        0.0.0.0:*               LISTEN
tcp        0      0 10.66.77.1:12345        10.66.77.6:46496        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50322        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50326        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50158        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:37800        ESTABLISHED
tcp        0      0 10.66.77.1:12345        10.66.77.6:50216        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50320        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50212        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:59144        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50246        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50156        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:41974        ESTABLISHED
tcp        0      0 10.66.77.1:12345        10.66.77.6:59150        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:47018        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:43676        ESTABLISHED
tcp        0      0 10.66.77.1:12345        10.66.77.6:43690        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:43554        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:46562        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:37818        ESTABLISHED
tcp        0      0 10.66.77.1:12345        10.66.77.6:60558        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:40460        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:37804        ESTABLISHED
tcp        0      0 10.66.77.1:12345        10.66.77.6:40444        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50162        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:46502        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:43692        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:60542        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:50390        ESTABLISHED
tcp        0      0 10.66.77.1:12345        10.66.77.6:47020        TIME_WAIT
tcp        0      0 10.66.77.1:12345        10.66.77.6:46578        TIME_WAIT


Logs with type http-connect
type = https-connect;

**Mar 19 10:59:13 openvpn2-tcp-us-east redsocks[2952]: getsockopt(fd=-1): Bad file descriptor**
Mar 19 10:59:13 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:37104->104.27.192.92:443]: relay, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Unknown error -1
Mar 19 10:59:13 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:37104->104.27.192.92:443]: dropping client @ state: 0
Mar 19 10:59:14 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:47786->172.217.9.46:443]: accepted
Mar 19 10:59:14 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:35264->216.58.192.132:443]: accepted
Mar 19 10:59:14 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:39446->216.58.212.131:443]: accepted
Mar 19 10:59:14 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:39450->216.58.212.131:443]: accepted
Mar 19 10:59:15 openvpn2-tcp-us-east redsocks[2952]: getsockopt(fd=-1): Bad file descriptor
Mar 19 10:59:15 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:45584->31.13.69.245:443]: relay, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Unknown error -1
Mar 19 10:59:15 openvpn2-tcp-us-east redsocks[2952]: [10.66.77.6:45584->31.13.69.245:443]: dropping client @ state: 0
Mar 19 11:07:02 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38916->104.27.192.92:443]: accepted
Mar 19 11:07:02 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38918->104.27.192.92:443]: accepted


Logs with http-connect
type = http-connect;

Mar 19 11:07:02 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38920->104.27.192.92:443]: accepted
Mar 19 11:07:02 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38922->104.27.192.92:443]: accepted
Mar 19 11:07:05 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:40236->5.135.165.173:80]: relay, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Success
Mar 19 11:07:05 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:40236->5.135.165.173:80]: dropping client @ state: 0
Mar 19 11:07:05 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:40238->5.135.165.173:80]: relay, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Success
Mar 19 11:07:05 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:40238->5.135.165.173:80]: dropping client @ state: 0
Mar 19 11:07:05 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:40244->5.135.165.173:80]: relay, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Success
Mar 19 11:07:05 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:40244->5.135.165.173:80]: dropping client @ state: 0
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38920->104.27.192.92:443]: dropping client @ state: 0
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38922->104.27.192.92:443]: relay, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Success
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38922->104.27.192.92:443]: dropping client @ state: 0
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38950->104.27.192.92:443]: accepted
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38952->104.27.192.92:443]: accepted
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38954->104.27.192.92:443]: accepted
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38952->104.27.192.92:443]: client, what: READING|0|EOF|0|0|0|0x0: Success
Mar 19 11:07:12 openvpn2-tcp-us-east redsocks[2687]: [10.66.77.6:38956->104.27.192.92:443]: accepted

Here are my IPtables NAT rules for reference.  **FYI this setup works perfectly well with redsocks v0.5**

# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDSOCKS   tcp  --  anywhere             anywhere             tcp dpt:http
REDSOCKS   tcp  --  anywhere             anywhere             tcp dpt:webcache
REDSOCKS   tcp  --  anywhere             anywhere             tcp dpt:https

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere

Chain REDSOCKS (3 references)
target     prot opt source               destination
RETURN     all  --  anywhere             10.0.0.0/8
RETURN     all  --  anywhere             loopback/8
RETURN     all  --  anywhere             192.0.0.0/8
RETURN     all  --  anywhere             172.16.0.0/12
RETURN     all  --  anywhere             default/8
REDIRECT   tcp  --  anywhere             anywhere             redir ports 12345

**Comment by john-d13** [comment]
I tweaked my fw rules and got things to start working using type=http-connect method albeit very slow. I am still seeing lots of TCP connection timeouts between my local network and the local redsocks listener.  

Maybe I can explain further my objective,  

IPTables PREROUTING rule will forward incoming TCP 80,443,8080 connections to the redsocks2 listener on the tun0 interface then redirect to a remote regular non-transparent http(s) proxy.  This remote proxy uses simple GET for HTTP and CONNECT for HTTPS.   

I can forward http via IPtables and bypass redsocks altogether but isint type=https-connect supposed to natively support https redirection?

Here is my error log when attempting to use type=https-connect.  

Mar 19 14:36:14 openvpn2-tcp-us-east redsocks[2765]: [10.66.77.6:58316->52.84.64.73:443]: accepted
Mar 19 14:36:14 openvpn2-tcp-us-east redsocks[2765]: [10.66.77.6:39788->172.217.9.46:443]: accepted
Mar 19 14:36:14 openvpn2-tcp-us-east redsocks[2765]: [10.66.77.6:43518->104.27.193.92:443]: accepted
Mar 19 14:36:16 openvpn2-tcp-us-east redsocks[2765]: [10.66.77.6:45102->63.251.114.137:443]: SSL Error: SSL routines SSL23_GET_SERVER_HELLO: unknown protocol: Success
Mar 19 14:36:16 openvpn2-tcp-us-east redsocks[2765]: [10.66.77.6:45102->63.251.114.137:443]: relay, what: 0|0|0|ERROR|0|0|0x0: Success
Mar 19 14:36:16 openvpn2-tcp-us-east redsocks[2765]: [10.66.77.6:45102->63.251.114.137:443]: dropping client @ state: 0
Mar 19 14:36:16 openvpn2-tcp-us-east redsocks[2765]: [10.66.77.6:45150->63.251.114.137:443]: accepted

Is there something you can suggest for optimal settings in my type of scenario ?

**Comment by semigodking** [comment]
@john-d13 , you should try removing 'interface = tun0;' from your config file or changing it to another interface.  This line specifies interface redsocks used for egress traffic.  I do not think you want egress traffic go out via VPN.  When tun0 is not interface for default route, you could simple remove this line. When tun0 is for default route, you need to replace the interface with interface you want for egress traffic.

**Comment by john-d13** [comment]
That seems to have improved throughput, granted there are other variables that can be playing a role also.  Can you please clarify these final points so I can rest assured performance is acceptable.

1. What difference between http-connect and **https-connect** method type.  If I invoke the https-connect, redsocks generates the SSL Errors.   If I use http-connect I can successfully redirect HTTPS "CONNECT" packets to my remote HTTPS proxy.  So whats the point of using https-connect?

```
1521552291.876075 debug https-connect.c:153 httpsc_event_cb(...) [10.66.77.6:44826->50.17.194.115:443]: relay, what: 0|0|0|ERROR|0|0|0x0: Success
1521552291.876081 debug redsocks.c:410 redsocks_drop_client(...) [10.66.77.6:44826->50.17.194.115:443]: dropping client @ state: 0
1521552292.059417 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:43164->54.225.178.207:443]: accepted
1521552292.136432 debug https-connect.c:78 log_ssl_error(...) [10.66.77.6:43164->54.225.178.207:443]: SSL Error: SSL routines SSL23_GET_SERVER_HELLO: unknown protocol: Success
1521552292.136476 debug https-connect.c:153 httpsc_event_cb(...) [10.66.77.6:43164->54.225.178.207:443]: relay, what: 0|0|0|ERROR|0|0|0x0: Success
1521552292.136485 debug redsocks.c:410 redsocks_drop_client(...) [10.66.77.6:43164->54.225.178.207:443]: dropping client @ state: 0
1521552292.320065 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:43168->54.225.178.207:443]: accepted
1521552292.396916 debug https-connect.c:78 log_ssl_error(...) [10.66.77.6:43168->54.225.178.207:443]: SSL Error: SSL routines SSL23_GET_SERVER_HELLO: unknown protocol: Success
1521552292.396949 debug https-connect.c:153 httpsc_event_cb(...) [10.66.77.6:43168->54.225.178.207:443]: relay, what: 0|0|0|ERROR|0|0|0x0: Success
1521552292.396955 debug redsocks.c:410 redsocks_drop_client(...) [10.66.77.6:43168->54.225.178.207:443]: dropping client @ state: 0
1521552292.579926 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:43170->54.225.178.207:443]: accepted
1521552292.656877 debug https-connect.c:78 log_ssl_error(...) [10.66.77.6:43170->54.225.178.207:443]: SSL Error: SSL routines SSL23_GET_SERVER_HELLO: unknown protocol

**2.  process_shutdown_on_write** in the debug log.  Are these messages expected or the result of an unexpected event/error.  Can you analyze these logs please:

```
521552120.672518 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:34552->31.13.80.34:443]: accepted
1521552120.813769 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:48946->172.217.0.2:443]: accepted
1521552125.289858 debug redsocks.c:511 redsocks_event_error(...) [10.66.77.6:56738->8.43.72.22:80]: client, what: READING|0|EOF|0|0|0|0x0: Success
1521552125.294055 debug redsocks.c:511 redsocks_event_error(...) [10.66.77.6:56740->8.43.72.22:80]: client, what: READING|0|EOF|0|0|0|0x0: Success
1521552125.301419 debug redsocks.c:511 redsocks_event_error(...) [10.66.77.6:39742->52.44.141.43:80]: client, what: READING|0|EOF|0|0|0|0x0: Success
1521552125.302109 debug redsocks.c:511 redsocks_event_error(...) [10.66.77.6:39744->52.44.141.43:80]: client, what: READING|0|EOF|0|0|0|0x0: Success
1521552125.673027 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:50348->172.217.4.74:443]: accepted
1521552130.738974 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:35270->130.211.37.21:443]: accepted
1521552132.560926 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:56788->8.43.72.22:80]: accepted
1521552132.790225 debug redsocks.c:398 redsocks_start_relay(...) [10.66.77.6:56788->8.43.72.22:80]: data relaying started
1521552132.790265 debug redsocks.c:310 process_shutdown_on_write_(...) [10.66.77.6:56788->8.43.72.22:80]: WCB relay, fs: 0, ts: 0, fin: 3987, fout: 0, tin: 0
1521552132.790288 debug redsocks.c:310 process_shutdown_on_write_(...) [10.66.77.6:56788->8.43.72.22:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 3987, tin: 0
1521552132.790311 debug redsocks.c:310 process_shutdown_on_write_(...) [10.66.77.6:56788->8.43.72.22:80]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1521552133.301273 debug redsocks.c:284 redsocks_relay_readcb(...) [10.66.77.6:56788->8.43.72.22:80]: RCB relay, in: 2896
1521552133.301351 debug redsocks.c:310 process_shutdown_on_write_(...) [10.66.77.6:56788->8.43.72.22:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1521552133.301613 debug redsocks.c:284 redsocks_relay_readcb(...) [10.66.77.6:56788->8.43.72.22:80]: RCB relay, in: 1620
1521552133.301648 debug redsocks.c:310 process_shutdown_on_write_(...) [10.66.77.6:56788->8.43.72.22:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1521552135.689061 debug redsocks.c:825 redsocks_accept_client(...) [10.66.77.6:49008->172.217.0.2:443]: accepted
1521552135.896231 debug redsocks.c:398 redsocks_start_relay(...) [10.66.77.6:49008->172.217.0.2:443]: data relaying started
1521552135.896279 debug redsocks.c:310 process_shutdown_on_write_(...) [10.66.77.6:49008->172.217.0.2:443]: WCB relay, fs: 0, ts: 0, fin: 517, fout: 0, tin: 0
```
```
**3. File Descriptors tuning**

With Redsocks v 0.5 I was able to tune the open file descriptors used by Redsocks process.  My system max is set to ulimit -n 64000, however, redsocks by default only sets a min fd value of 1024 and max 4096.  This was tunable invoking the following parameters in the config file but seems like these are deprecated in redsocks2 (server does not understand the value)

    // Set maximum number of open file descriptors (also known as `ulimit -n`).
        //  0 -- do not modify startup limit (default)
        //  rlimit_nofile = 10000;

        // Set maximum number of served connections. Default is to deduce safe
        // limit from `splice` setting and RLIMIT_NOFILE.
        //  redsocks_conn_max = 10000;


cat /proc/5253/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             1845                 1845                 processes
**Max open files            1024                 4096                 files**
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       1845                 1845                 signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us


[root@openvpn2-tcp-us-east ~]# ulimit -n
64000

**Comment by john-d13** [comment]
What logic is redsocks using to set its max fd ?  As mentioned, in previous version it was a configurable option in the .conf file but those commands have since been deprecated.

**Comment by semigodking** [comment]
Redsocks does not do that. Max fd is controlled by system soft limit and
hard limit.  See
https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/
